"""Removed unique key from teams' names.

Revision ID: 5e2ae7712fe9
Revises: 57314d516505
Create Date: 2025-03-08 06:56:35.672827

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e2ae7712fe9'
down_revision: Union[str, None] = '57314d516505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_name_key', 'team', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('team_name_key', 'team', ['name'])
    # ### end Alembic commands ###
